- submitted: 2024-01-04
  supervisor: Eugene Syriani, Louis-Edouard Lafontant
  status: open
  type: regular
  title: Café sans-fil (suite)
  description: >
    Ce projet pilote vise à améliorer le service des cafés étudiants de l'UdeM. 
    Lors de la session d'automne, nous avons développé l'infrastructure du projet (BD, API, CI/CD) et créé un prototype fonctionnel (<a href="https://cafesansfil.onrender.com/">application web</a>).
    À date, l'application facilite la découverte des cafés et leurs produits, la prise de commandes (pour ramassage) et la gestion des cafés (infos de base, menu, bénévoles).

    Cette session, nous voulons valider le prototype, améliorer la recherche et le système d'identification de produits et développer le segment social.
    En vue d'une première version public (version 1.0), nous voulons intégrer l'application avec quelques cafés étudiants.
    
    Plus de détails sur le <a href="https://github.com/ceduni/udem-cafe">répertoire GitHub du projet</a>
  contact: louis.edouard.lafontant@umontreal.ca

- submitted: 2023-10-26
  supervisor: Max Mignotte
  type: regular
  status: open
  title: Généralisation en 3D et parallélisation sur GPU d'un code C++/Linux
  description: >
    L'objectif de ce travail est d'une part (1) de convertir un programme existant initialement en C++/Linux qui applique un certain noyau de
    filtrage 2D sur une image (un tableau 2D de données flottantes) en 3D, c-a-d, utilisant un noyau de filtrage 3D sur un cube d'images
    (opération très facile) mais surtout (2) de programmer ce code en C++/Linux sur GPU avec CUDA, (carte graphique Nvidia du style RTX
    3090 ou supérieure).
  contact: mignotte@iro.umontreal.ca
  
- submitted: 2023-09-25
  supervisor: Stefan Monnier
  type: regular
  status: open
  title: Regexp-match par backtracking en temps linéaire
  description: >
    Le filtrage par expressions régulière se fait théoriquement en temps linéaire, mais en pratique il est courant d'utiliser
    une implantation par backtracking qui souffre d'une complexité exponentielle.  
    Dans ce projet vous prendrez une telle implantation (celle d'Emacs) et vous lui rendrez sa complexité linéaire en ajoutant "simplement" une table de mémoization.
  contact: monnier@iro.umontreal.ca

- submitted: 2023-04-28
  supervisor: Eric Lacourse
  type: regular
  status: open
  title: Développement de la librairie StepMix pour les modèles de mélange généralisés
  description: >
    Les étudiants peuvent avoir accès au projet StepMix Python à <a href="https://github.com/Labo-Lacourse/stepmix">cette adresse</a>. 
    Le développement de StepMix passe par le biais de différentes extensions: 
    
    1) Développer des modèles pour différentes distributions des valeurs observées (censored-normal, Poisson, Zero-Inflated Poisson) 

    2) Extension pour des données longitudinales 
    
    3) Extensions pour des problèmes en grande dimension (régularisation et modèle de mélange d'analyse factorielle), etc. 
    
    Ce sont tous des projets/extensions qui peuvent être réalisés par plusieurs équipe qui travaillent parallèlement.
  contact: eric.lacourse@umontreal.ca

- submitted: 2023-04-18
  supervisor: Eugene Syriani, Louis-Edouard Lafontant
  status: open
  type: regular
  title: Café sans-fil
  description: >
    Ce projet pilote vise à améliorer le service des cafés étudiants de l'UdeM. 
    Il consiste à développer une application web complète (backend + frontend) facilitant la recherche de cafés et produits, la prise de commandes et la gestion du menu et de l'inventaire. 
    L'application sera accessible à tout membre de l'UdeM (étudiant, employé, professeur, chercheur...).et offrira certains rôles (membre, staff, admin) donnant accès à certaines fonctionnalités. 
    L'infrastructure de l'application consiste principalement en une base de données assurant le stockage efficace des données, une API traitant les requêtes envoyées par les clients, 
    et une application web permettant aux utilisateurs de visualiser et interagir avec les données de l'application. 
    
    Plus de détails sur le <a href="https://github.com/ceduni/udem-cafe">répertoire GitHub du projet</a>
  contact: louis.edouard.lafontant@umontreal.ca
  realized:
    on: Automne 2023
    by:
      - name: Southidej Oudanonh
        email: southidej.oudanonh@umontreal.ca
      - name: Axel Zareb
        email: axel.zareb@umontreal.ca

- submitted: 2022-04-07
  supervisor: Glen Berseth
  title: Improving computer vision
  description: >
    The main goal of this project is to rethink how we manipulate signals in machine learning, and to propose a new convolutional network architectures.
  contact: gberseth@iro.umontreal.ca

- submitted: 2022-04-07
  supervisor: Glen Berseth
  status: open
  title: Generaliation in reinforcement learning
  description: >
    This project will focus on methods that provide generalization capabilities to deep reinforcement learning agents.
    This includes studying methods that learn-to-learn and use this skill to learn how to adapt to changes in the types of tasks they are trying to solve.
    The work can also include studying how agents can learn better representations that allow agents to be robust to change which enables generalization.
  contact: gberseth@iro.umontreal.ca
  
- submitted: 2022-04-15
  supervisor: Guy Lapalme, Lena Krause
  status: open
  title: MONA (iOS)
  description: >
    MONA est application mobile libre et open source qui permet de découvrir, photographier et collectionner l'art public à Montréal, 
    développée comme projet de recherche au sein d'une équipe multi-disciplinaire.

    Le projet consiste à poursuivre le développement de l'application iOS (Swift) et requiert l'utilisation d'un MacOS et d'un iPhone. 


    <b>Tâches prévues:</b>
    
    - Ajout d'un nouveau type de données (patrimoine)

    - Amélioration des paramètres utilisateur (compte utilisateur, notifications)
    
    - Fonctionnalité de partage sur les réseaux sociaux dont Instagram en priorité
    
    - Expérimentation avec l'ajout de contenus multimédia (photo, vidéo, balado) en collaboration avec la personne responsable de l'API"
  contact: lapalme@iro.umontreal.ca; info@monamontreal.org

- submitted: 2022-04-15
  supervisor: 'Guy Lapalme, Lena Krause'
  status: open
  title: MONA (Android)
  description: >
    MONA est application mobile libre et open source qui permet de découvrir, photographier et collectionner l'art public à Montréal, 
    développée comme projet de recherche au sein d'une équipe multi-disciplinaire.

    Le projet consiste à poursuivre le développement de l'application Android (Kotlin). 


    <b>Tâches prévues:</b>

    - Poursuivre l'implémentation de la nouvelle architecture (le code est en restructuration majeure pour faciliter la maintenance et favoriser une organisation modulaire)
    
    - Ajout d'un nouveau type de données (patrimoine)
    
    - Vérifier le bon fonctionnement de l'envoi des données utilisateur vers le serveur
    
    - Autres fonctionnalités (paramètres, partage, multimédia) si la restructuration avance bien
  contact: lapalme@iro.umontreal.ca; info@monamontreal.org

- submitted: 2022-04-15
  supervisor: Guy Lapalme, Lena Krause
  status: open
  title: MONA (serveur)
  description: >
    MONA est application mobile libre et open source qui permet de découvrir, photographier et collectionner l'art public à Montréal, 
    développée comme projet de recherche au sein d'une équipe multi-disciplinaire.

    Le projet consiste à poursuivre le développement de l'interface admin (PHP/laravel et vue.js). 


    <b>Tâches prévues:</b>

    - Terminer l'implémentation du versionnement et de l'historique de modification pour permettre la modification des données depuis l'interface admin
    
    - Collaborer avec la personne responsable de l'API pour garantir la validité des données
    
    - Faire un ménage dans les données existantes: terminer le tri des doublons, supprimer les tests des développeur·se·s front-end et identifier les "vrais" contenus
    
    - Concevoir et implémenter un tableau de bord analytique à propos des données MONA"
  contact: lapalme@iro.umontreal.ca; info@monamontreal.org

- submitted: 2022-05-02
  supervisor: Esma Aimeur
  status: open
  title: Simulate a functioning social media environment
  description: >
    With the proliferation of social medial platforms, it is more relevant now than ever before to focus on the protection of the users' privacy. 
    Most targeted threats are based on monitoring the individuals' actions and exploiting the behavioral biases that they exhibit.

    To counter this, the proposed  project aims to simulate a functioning social media environment in order to predict future threats, 
    study user vulnerabilities, and ultimately propose privacy-preserving solutions. 
    The task is to simulate social media activity by implementing a platform where a new user profile can be created, connections can be made, posts
    can be published, etc.

    The student would need to apply their dynamic web programming skills to achieve this.
  contact: aimeur@iro.umontreal.ca

- submitted: 2022-05-02
  supervisor: Esma Aimeur
  status: open
  title: Fake news detection based on predicting the veracity of online news through source analysis
  description: >
    Fake news detection on social media presents unique characteristics and challenges which make the search for a solution anything but trivial. 
    Consequently, automatic fake news detection remains a huge challenge, primarily because the content is designed in a way that it extremely resembles
    the truth to deceive users, and it is often hard to determine its veracity by AI alone without additional information from third parties.


    The main goal of this project is to develop a software solution to detect fake news based on predicting the veracity of online news through source analysis. 
    The idea of the source analysis task is to check whether the news has been already published by trusted sources on the web.


    The main tasks of the solution are to i) process the web, ii) check the trustworthiness of the sources, iii) and verify the news directly from its official source. The software solution may include but is not limited to, the use of two factors to verify the credibility and the nature of online news: trusted news sources and news publication date."
  contact: aimeur@iro.umontreal.ca

- submitted: 2022-05-05
  supervisor: Eugene Syriani
  status: open
  title: App pour la grande éclipse 2024
  description: >
    Vous aimez l’astronomie et aimeriez participer à la création d’une app Android et iOS pour la grande éclipse solaire qui aura lieu en 2024?


    Nous sommes à la recherche de 2 ou 3 étudiant.e.s intéressé.e.s à suivre le cours projet IFT3150 cet été. 
    Le but est de créer une app éducative permettant aux utilisateurs de comprendre le phénomène des éclipses solaires et de suivre le déroulement de
    celle-ci en temps réel, en fonction de leur positionnement lors de l’événement.
    
    Le projet sera conjointement supervisé par la Fédération des astronomes amateurs du Québec. 
    Les atouts recherchés pour ce projet sont une familiarité avec la plateforme Xamarin, langage C#, SQL et développement d’application mobile.
  contact: syriani@iro.umontreal.ca

- submitted: 2022-09-19
  supervisor: Michalis Famelis
  status: open
  title: "DRUIDE: tracing uncertainty in software"
  description: >
    When building software systems, we encounter different kinds of uncertainty that concerns lack of information about how our designs should look like. 
    DRUIDE ("Design and Requirements Uncertainty IDE") is a proposed framework for modelling and tracing such uncertainty. 
    In this project, we will create a DRUIDE prototype.
  contact: famelis@iro.umontreal.ca

- submitted: 2022-12-08
  supervisor: Houari Sahraoui
  status: open
  title: Application Web de reservation à la Station Biologique des Laurentides
  description: >
    La Station de biologie des Laurentides (SBL) de l’Université de Montréal est un lieu actif de recherche scientifique et d’enseignement depuis plus de 50 ans. 
    Il est également possible d'y faire des retraites de rédaction, des séjours pendant lesquels les étudiants concentrent leurs efforts 
    sur l’avancée de leur thèse ou mémoire, dans un cadre enchanteur et ressourçant. La SBL occupe un territoire de 16,8 km carrés de forêt, incluant 16 lacs. 
    Elle est localisée dans les Laurentides, une région considérée comme un « hotspot » de biodiversité du Québec.


    L’utilisation de la SBL est en hausse constante depuis 2011 et cette popularité grandissante amène le besoin de certains ajustements, 
    dont celui du système de réservation. Ce dernier ayant été mis en place il y a plusieurs années, il consiste essentiellement en une suite 
    d’opérations à effectuer manuellement, ce qui augmente le risque d’erreur lors de la manipulation de l’information et devient rapidement coûteux en temps.


    Récemment, un nouveau système de réservation a été développé sous forme d’une application web (PHP- Laravel). Il consiste à automatiser les réservations 
    d’individus ou de groupes. Il inclut diverses fonctionnalités, comme la réservation des chambres, la réservation de canots, etc. 
    Ce projet consiste à ajouter de nouvelles fonctionnalités dont un système de paiement automatisé en ligne, à tester l’application web 
    (unitaire, système et acceptation), ainsi qu'à la déployer un serveur.
  contact: sahraouh@iro.umontreal.ca